### ISSUE TITLE
With your permission...

### ISSUE THREAD

**Issue by jgravelle** [madtank/autogenstudio-skills#6]
...I'd like to include the skills from your library in AutoGroq™ [https://github.com/jgravelle/AutoGroq] making certain you were credited in the comments.

Over four thousand viewers saw my endorsement of your work here:  https://www.youtube.com/watch?v=w29wPOEHedQ&t=260s 

...and this would a) save them a step; and b) offer you some well-deserved notoriety.  Let me know... -jjg

**Comment by madtank** [comment]
Looks good. I'm interested in trying out AutoGroq to generate some workflows for Autogen studio, looks like good time saver.

**Comment by madtank** [comment]
Do you plan to fork from this repo? I could take some time to maintain the skill library.

**Comment by jgravelle** [comment]
Thanks, but I really want people to handle their own bells and whistles.  Giving them a dozen or so open-source skills lets them hit the ground running.  Appreciate it...!
